GitLab CI: change artifact name; fix Buster build;  add Ubuntu Focal build; add Clang code analyze jobs

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -10,6 +10,7 @@ variables:
   # Git strategy https://docs.gitlab.com/ee/ci/large_repositories/#git-strategy
   GIT_STRATEGY: clone
 
+#Build Stage
 
 Raspbian:Stretch:
   stage: build
@@ -31,7 +32,7 @@ Raspbian:Stretch:
   after_script:
     - docker run --volume $(pwd):/artifact $CI_REGISTRY_IMAGE:latest
   artifacts:
-    name: "$CI_JOB_NAME"
+    name: "FotoBox_$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
     paths:
       - FotoBox_RasPi_Stretch.tar.gz
 
@@ -53,9 +54,9 @@ Raspbian:Buster:
     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
     - docker push $CI_REGISTRY_IMAGE:latest
   after_script:
-    - docker run --volume $(pwd):/artifact buildfotobox
+    - docker run --volume $(pwd):/artifact $CI_REGISTRY_IMAGE:latest
   artifacts:
-    name: "$CI_JOB_NAME"
+    name: "FotoBox_$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
     paths:
       - FotoBox_RasPi_Buster.tar.gz
 
@@ -77,13 +78,14 @@ Raspbian:Bullseye:
     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
     - docker push $CI_REGISTRY_IMAGE:latest
   after_script:
-    - docker run --volume $(pwd):/artifact buildfotobox
+    - docker run --volume $(pwd):/artifact $CI_REGISTRY_IMAGE:latest
   # It's allowed to fail because currently unreleased OS
   allow_failure: true
   artifacts:
-    name: "$CI_JOB_NAME"
+    name: "FotoBox_$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
     paths:
       - FotoBox_RasPi_Bullseye.tar.gz
+
 
 Ubuntu:Xenial:QMake:
   stage: build
@@ -104,7 +106,7 @@ Ubuntu:Xenial:QMake:
   after_script:
     - tar -cvzf ./FotoBox_Ubuntu_Xenial.tar.gz -C . FotoBox -C ./other/ README.pdf install_dependencies.sh
   artifacts:
-    name: "$CI_JOB_NAME"
+    name: "FotoBox_$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
     paths:
       - FotoBox_Ubuntu_Xenial.tar.gz
 
@@ -117,6 +119,7 @@ Ubuntu:Bionic:CMake:
     - apt-get install -qq
         build-essential
         ccache
+        cmake
         qt5-default
         qttools5-dev
     - cmake --version
@@ -125,9 +128,137 @@ Ubuntu:Bionic:CMake:
   script:
     - cmake CMakeLists.txt -G "Unix Makefiles"
     - make -j$(nproc)
-  after_script:
-    - tar -cvzf ./FotoBox_Ubuntu_Bionic.tar.gz -C . FotoBox -C ./other/ README.pdf install_dependencies.sh
   artifacts:
-    name: "$CI_JOB_NAME"
+    name: "FotoBox_$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
+    expose_as: "artifact_UbuntuBionic"
     paths:
-      - FotoBox_Ubuntu_Bionic.tar.gz
+      - FotoBox
+      - other/README.pdf
+      - other/install_dependencies.sh
+
+Ubuntu:Focal:CMake:
+  stage: build
+  # Official Ubuntu Image https://hub.docker.com/_/ubuntu
+  image: ubuntu:focal
+  before_script:
+    - apt-get update -qq
+    - apt-get install -qq
+        build-essential
+        ccache
+        cmake
+        qt5-default
+        qttools5-dev
+    - cmake --version
+    - gcc --version
+    - qmake --version
+  script:
+    - cmake CMakeLists.txt -G "Unix Makefiles"
+    - make -j$(nproc)
+  artifacts:
+    name: "FotoBox_$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
+    expose_as: "artifact_UbuntuFocal"
+    paths:
+      - FotoBox
+      - other/README.pdf
+      - other/install_dependencies.sh
+
+# Analyze stage
+
+Clang:
+  stage: analyze
+  # Official Ubuntu Image https://hub.docker.com/_/ubuntu
+  image: ubuntu:focal
+  variables:
+    CC: "clang-8"
+    CXX: "clang++-8"
+  before_script:
+    - apt-get update -qq
+    - apt-get install -qq
+        cmake
+        qt5-default
+        qttools5-dev
+        clang-8
+    - cmake --version
+    - clang++-8 --version
+  script:
+    # '-Werror' -> Turn warnings into errors
+    # https://releases.llvm.org/8.0.0/tools/clang/docs/DiagnosticsReference.html
+    - cmake CMakeLists.txt -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra -Wpedantic"
+    - make -j$(nproc) 2>&1 | tee output.txt
+  artifacts:
+    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
+    expose_as: "Clang"
+    when: on_failure
+    paths:
+      - output.txt
+
+ClangTidy:
+  stage: analyze
+  # Official Ubuntu Image https://hub.docker.com/_/ubuntu
+  image: ubuntu:focal
+  variables:
+    CC: "clang-8"
+    CXX: "clang++-8"
+    CLANG_TIDY: "clang-tidy-8"
+  before_script:
+    - apt-get update -qq
+    - apt-get install -qq
+        cmake
+        qt5-default
+        qttools5-dev
+        clang-8
+        llvm-8
+        clang-tidy-8
+    - cmake --version
+    - clang++-8 --version
+  script:
+    - cmake CMakeLists.txt -G "Unix Makefiles" -DCMAKE_CXX_FLAGS="-Wno-everything" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_CLANG_TIDY=ON
+    - make -j$(nproc)
+    - make -j$(nproc) tidy 2>&1 | tee output.txt
+    - |
+      if [[ -n $(grep -v "_autogen" output.txt | grep "warning: ") ]] || [[ -n $(grep -v "_autogen" output.txt | grep "error: ") ]]; then
+        echo -e "\033[1;31m\xE2\x9C\x93 clang tidy failed!\033[0m";
+        exit 1;
+      else
+        echo -e "\033[1;32m\xE2\x9C\x93 clang tidy passed!\033[0m";
+      fi
+  artifacts:
+    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
+    expose_as: "ClangTidy"
+    when: on_failure
+    paths:
+      - output.txt
+
+Clazy:
+  stage: analyze
+  # Official Ubuntu Image https://hub.docker.com/_/ubuntu
+  image: ubuntu:focal
+  before_script:
+    - apt-get update -qq
+    - apt-get install -qq
+        cmake
+        qt5-default
+        qttools5-dev
+        wget
+        libfuse
+    - wget --output-document=clazy.AppImage https://downloads.kdab.com/clazy/1.6/Clazy-x86_64-1.6.AppImage
+    - chmod +x clazy.AppImage
+    - ./clazy.AppImage --version
+    - ./clazy.AppImage --standalone -version
+  script:
+    - cmake CMakeLists.txt -G "Unix Makefiles" -DCMAKE_CXX_FLAGS="-Wno-everything" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_CLANG_CLAZY=ON
+    - make -j$(nproc)
+    - make -j$(nproc) clazy 2>&1 | tee output.txt
+    - |
+      if [[ -n $(grep -v "_autogen" output.txt | grep "warning: ") ]] || [[ -n $(grep -v "_autogen" output.txt | grep "error: ") ]]; then
+        echo -e "\033[1;31m\xE2\x9C\x93 clang clazy failed!\033[0m";
+        exit 1;
+      else
+        echo -e "\033[1;32m\xE2\x9C\x93 clang clazy passed!\033[0m";
+      fi
+  artifacts:
+    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
+    expose_as: "ClangClazy"
+    when: on_failure
+    paths:
+      - output.txt
