test CI

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -177,6 +177,13 @@ Clang:
     # https://releases.llvm.org/8.0.0/tools/clang/docs/DiagnosticsReference.html
     - cmake CMakeLists.txt -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra -Wpedantic"
     - make -j$(nproc) 2>&1 | tee output.txt
+    - |
+      if [[ -n $(grep -v "_autogen" output.txt | grep "warning: ") ]] || [[ -n $(grep -v "_autogen" output.txt | grep "error: ") ]]; then
+        echo -e "\033[1;31m\xE2\x9C\x93 clang diagnostic flags failed!\033[0m";
+        exit 1;
+      else
+        echo -e "\033[1;32m\xE2\x9C\x93 clang diagnostic flags passed!\033[0m";
+      fi
   artifacts:
     name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
     expose_as: "Clang"
diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -146,6 +146,13 @@ jobs:
         # https://releases.llvm.org/8.0.0/tools/clang/docs/DiagnosticsReference.html
         - cmake CMakeLists.txt -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra -Wpedantic"
         - make -j$(nproc) 2>&1 | tee output.txt
+        - |
+          if [[ -n $(grep -v "_autogen" output.txt | grep "warning: ") ]] || [[ -n $(grep -v "_autogen" output.txt | grep "error: ") ]]; then
+            echo -e "\033[1;31m\xE2\x9C\x93 clang diagnostic flags failed!\033[0m";
+            exit 1;
+          else
+            echo -e "\033[1;32m\xE2\x9C\x93 clang diagnostic flags passed!\033[0m";
+          fi
 
     - name: "Ubuntu Bionic Beaver CMake Debug clang tidy 8"
       os: linux
