optimize clang builds; test tidy and clazy if working fine (Travis CI build should fail);

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -101,8 +101,8 @@ matrix:
         - cmake --version
         - clang++-7 --version
       script:
-        # QtCreator -> Analyze -> clang -> Rule: "Clang ... almost everything" + -Wno-padded
-        - cmake CMakeLists.txt -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-unused-macros -Wno-newline-eof -Wno-exit-time-destructors -Wno-global-constructors -Wno-gnu-zero-variadic-macro-arguments -Wno-documentation -Wno-shadow -Wno-switch-enum -Wno-missing-prototypes -Wno-used-but-marked-unused -Wno-padded"
+        # QtCreator -> Analyze -> clang -> Rule: "Clang ... almost everything" rules and added '-Wno-padded -Werror'
+        - cmake CMakeLists.txt -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror -Wno-padded -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-unused-macros -Wno-newline-eof -Wno-exit-time-destructors -Wno-global-constructors -Wno-gnu-zero-variadic-macro-arguments -Wno-documentation -Wno-shadow -Wno-switch-enum -Wno-missing-prototypes -Wno-used-but-marked-unused"
         - make
 
     - name: "Ubuntu Xenial CMake Debug clang tidy 7"
@@ -163,7 +163,16 @@ matrix:
       script:
         - cmake CMakeLists.txt -G "Unix Makefiles" -DCMAKE_CXX_FLAGS="-Wno-everything" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_CLANG_CLAZY=ON
         - make -j2
-        - make clazy
+        - make clazy 2>&1 | tee output.txt
+        - |
+          if [[ -n $(grep -v "_autogen" output.txt | grep "warning: ") ]] || [[ -n $(grep -v "_autogen" output.txt | grep "error: ") ]]; then
+            echo "clang tidy failed:"
+            echo ""
+            grep -v "_autogen" output.txt | grep --color -E '^|warning: |error: '
+            exit 1;
+          else
+            echo -e "\033[1;32m\xE2\x9C\x93 clazy passed!\033[0m";
+          fi
 
     - name: "macOS Doxygen"
       os: osx
